name: subspace
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.0
  floor: ^1.4.2
  retrofit: ^4.0.2
  flutter_hooks: ^0.18.3
  cached_network_image: ^3.2.3
  dio: ^5.3.3
  ionicons: ^0.2.2
  connectivity_plus: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^8.0.0
  floor_generator: ^1.4.2
  build_runner: 


flutter:

  
  uses-material-design: true

  